import { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'pt', label: 'Português' },
  { code: 'es', label: 'Español' },
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' }
];

export const TRANSLATIONS = {
  pt: {
    inicio: 'Início',
    animes: 'Animes',
    favoritos: 'Favoritos',
    menu: 'Menu',
    emAlta: 'Em alta',
    novosEpisodios: 'Novos episódios',
    recemAdicionados: 'Recém adicionados',
    lancamento: 'Lançamento',
    aventura: 'Aventura',
    comedia: 'Comédia',
    romance: 'Romance',
    talvezGoste: 'Talvez você goste',
    tudo: 'Tudo',
    filmes: 'Filmes',
    series: 'Séries',
    buscar: 'O que está procurando?',
    categorias: 'Categorias',
    nenhumResultado: 'Nenhum resultado encontrado',
    nenhumFavorito: 'Nenhum favorito encontrado',
    episodio: 'Episódio',
    emExibicao: 'Em exibição',
    sinopseIndisponivel: 'Sinopse não disponível.',
    popularidade: 'Popularidade',
    criarPerfil: 'Criar perfil',
    editarPerfil: 'Editar Perfil',
    privacidade: 'Privacidade',
    ajuda: 'Ajuda',
    sobre: 'Sobre',
    linguagem: 'Linguagem',
    sairDoPerfil: 'Sair do perfil',
    sairLimpar: 'Sair e limpar dados',
    cancelar: 'Cancelar',
    aoSalvar: 'Ao sair, todos os seus favoritos serão perdidos permanentemente. Deseja continuar?',
    nome: 'Nome',
    username: 'Username',
    salvar: 'Salvar',
    entrouEm: 'Entrou em',
    hoje: 'hoje',
    privacidadeTitulo: 'Privacidade',
    privacidadeTexto: 'Este aplicativo não coleta, armazena ou compartilha dados pessoais dos usuários. As informações de perfil e favoritos são armazenadas localmente no seu dispositivo e podem ser removidas a qualquer momento.',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'Créditos',
    desenvolvedor: 'Desenvolvido por',
    design: 'Design e implementação por Yoshikawa Systems',
    direitos: 'Direitos Autorais',
    isencao: 'Isenção de Responsabilidade',
    isencaoTexto: 'Este site não hospeda nenhum conteúdo. Utiliza APIs públicas de terceiros (TMDB) para indexação de informações. Qualquer violação de direitos autorais deve ser reportada diretamente aos provedores de conteúdo.',
    versao: 'Versão',
    anime: 'Anime',
    filme: 'Filme',
    serie: 'Série',
    politicaPrivacidade: 'Política de Privacidade',
    faleConosco: 'Fale conosco',
    versaoApp: 'Versão do app',
    releaseBuild: 'RELEASE BUILD',
    criePerfilBanner: 'Crie seu perfil para personalizar sua experiência!',
    userPadrao: '@user',
    criar: 'Criar',
    editar: 'Editar',
    perfil: 'Perfil',
    sair: 'Sair',
    voltar: 'Voltar',
    confirmar: 'Confirmar',
    linguagemTitulo: 'Idioma',
    selecioneIdioma: 'Selecione o idioma',
  },
  es: {
    inicio: 'Inicio',
    animes: 'Animes',
    favoritos: 'Favoritos',
    menu: 'Menú',
    emAlta: 'En tendencia',
    novosEpisodios: 'Nuevos episodios',
    recemAdicionados: 'Recién añadidos',
    lancamento: 'Lanzamiento',
    aventura: 'Aventura',
    comedia: 'Comedia',
    romance: 'Romance',
    talvezGoste: 'Quizás te guste',
    tudo: 'Todo',
    filmes: 'Películas',
    series: 'Series',
    buscar: '¿Qué estás buscando?',
    categorias: 'Categorías',
    nenhumResultado: 'No se encontraron resultados',
    nenhumFavorito: 'No se encontraron favoritos',
    episodio: 'Episodio',
    emExibicao: 'En emisión',
    sinopseIndisponivel: 'Sinopsis no disponible.',
    popularidade: 'Popularidad',
    criarPerfil: 'Crear perfil',
    editarPerfil: 'Editar perfil',
    privacidade: 'Privacidad',
    ajuda: 'Ayuda',
    sobre: 'Acerca de',
    linguagem: 'Idioma',
    sairDoPerfil: 'Salir del perfil',
    sairLimpar: 'Salir y borrar datos',
    cancelar: 'Cancelar',
    aoSalvar: 'Al salir, todos tus favoritos se perderán permanentemente. ¿Deseas continuar?',
    nome: 'Nombre',
    username: 'Usuario',
    salvar: 'Guardar',
    entrouEm: 'Se unió en',
    hoje: 'hoy',
    privacidadeTitulo: 'Privacidad',
    privacidadeTexto: 'Esta aplicación no recopila, almacena ni comparte datos personales de los usuarios. La información del perfil y los favoritos se almacenan localmente en tu dispositivo y se pueden eliminar en cualquier momento.',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'Créditos',
    desenvolvedor: 'Desarrollado por',
    design: 'Diseño e implementación por Yoshikawa Systems',
    direitos: 'Derechos de autor',
    isencao: 'Descargo de responsabilidad',
    isencaoTexto: 'Este sitio no aloja ningún contenido. Utiliza APIs públicas de terceros (TMDB) para indexar información. Cualquier infracción de derechos de autor debe informarse directamente a los proveedores de contenido.',
    versao: 'Versión',
    anime: 'Anime',
    filme: 'Película',
    serie: 'Serie',
    politicaPrivacidade: 'Política de privacidad',
    faleConosco: 'Contáctanos',
    versaoApp: 'Versión de la app',
    releaseBuild: 'VERSIÓN DE LANZAMIENTO',
    criePerfilBanner: '¡Crea tu perfil para personalizar tu experiencia!',
    userPadrao: '@usuario',
    criar: 'Crear',
    editar: 'Editar',
    perfil: 'Perfil',
    sair: 'Salir',
    voltar: 'Volver',
    confirmar: 'Confirmar',
    linguagemTitulo: 'Idioma',
    selecioneIdioma: 'Seleccionar idioma',
  },
  en: {
    inicio: 'Home',
    animes: 'Animes',
    favoritos: 'Favorites',
    menu: 'Menu',
    emAlta: 'Trending',
    novosEpisodios: 'New Episodes',
    recemAdicionados: 'Recently Added',
    lancamento: 'Now Playing',
    aventura: 'Adventure',
    comedia: 'Comedy',
    romance: 'Romance',
    talvezGoste: 'You Might Like',
    tudo: 'All',
    filmes: 'Movies',
    series: 'TV Shows',
    buscar: 'What are you looking for?',
    categorias: 'Categories',
    nenhumResultado: 'No results found',
    nenhumFavorito: 'No favorites found',
    episodio: 'Episode',
    emExibicao: 'Airing',
    sinopseIndisponivel: 'Synopsis not available.',
    popularidade: 'Popularity',
    criarPerfil: 'Create Profile',
    editarPerfil: 'Edit Profile',
    privacidade: 'Privacy',
    ajuda: 'Help',
    sobre: 'About',
    linguagem: 'Language',
    sairDoPerfil: 'Sign Out',
    sairLimpar: 'Sign out and clear data',
    cancelar: 'Cancel',
    aoSalvar: 'By signing out, all your favorites will be permanently lost. Do you wish to continue?',
    nome: 'Name',
    username: 'Username',
    salvar: 'Save',
    entrouEm: 'Joined in',
    hoje: 'today',
    privacidadeTitulo: 'Privacy',
    privacidadeTexto: 'This app does not collect, store, or share personal data. Profile and favorites are stored locally on your device and can be removed at any time.',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'Credits',
    desenvolvedor: 'Developed by',
    design: 'Design and implementation by Yoshikawa Systems',
    direitos: 'Copyright',
    isencao: 'Disclaimer',
    isencaoTexto: 'This site does not host any content. It uses public third-party APIs (TMDB) for content indexing. Any copyright infringement should be reported directly to the content providers.',
    versao: 'Version',
    anime: 'Anime',
    filme: 'Movie',
    serie: 'TV Show',
    politicaPrivacidade: 'Privacy Policy',
    faleConosco: 'Contact us',
    versaoApp: 'App version',
    releaseBuild: 'RELEASE BUILD',
    criePerfilBanner: 'Create your profile to personalize your experience!',
    userPadrao: '@user',
    criar: 'Create',
    editar: 'Edit',
    perfil: 'Profile',
    sair: 'Sign out',
    voltar: 'Back',
    confirmar: 'Confirm',
    linguagemTitulo: 'Language',
    selecioneIdioma: 'Select language',
  },
  ja: {
    inicio: 'ホーム',
    animes: 'アニメ',
    favoritos: 'お気に入り',
    menu: 'メニュー',
    emAlta: 'トレンド',
    novosEpisodios: '新エピソード',
    recemAdicionados: '最近追加',
    lancamento: '公開中',
    aventura: '冒険',
    comedia: 'コメディ',
    romance: 'ロマンス',
    talvezGoste: 'おすすめ',
    tudo: 'すべて',
    filmes: '映画',
    series: 'ドラマ',
    buscar: '何をお探しですか？',
    categorias: 'カテゴリ',
    nenhumResultado: '結果が見つかりません',
    nenhumFavorito: 'お気に入りがありません',
    episodio: 'エピソード',
    emExibicao: '放送中',
    sinopseIndisponivel: '概要はありません。',
    popularidade: '人気',
    criarPerfil: 'プロフィール作成',
    editarPerfil: 'プロフィール編集',
    privacidade: 'プライバシー',
    ajuda: 'ヘルプ',
    sobre: 'について',
    linguagem: '言語',
    sairDoPerfil: 'サインアウト',
    sairLimpar: 'サインアウトしてデータを消去',
    cancelar: 'キャンセル',
    aoSalvar: 'サインアウトすると、お気に入りが完全に失われます。続行しますか？',
    nome: '名前',
    username: 'ユーザー名',
    salvar: '保存',
    entrouEm: '参加日',
    hoje: '今日',
    privacidadeTitulo: 'プライバシー',
    privacidadeTexto: 'このアプリは個人データを収集、保存、共有しません。プロフィールとお気に入りはデバイスにローカルに保存され、いつでも削除できます。',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'クレジット',
    desenvolvedor: '開発者',
    design: 'Yoshikawa Systemsによるデザインと実装',
    direitos: '著作権',
    isencao: '免責事項',
    isencaoTexto: 'このサイトはコンテンツをホストしていません。公開されているサードパーティAPI（TMDB）を使用して情報をインデックスしています。著作権侵害は、直接コンテンツ提供者に報告してください。',
    versao: 'バージョン',
    anime: 'アニメ',
    filme: '映画',
    serie: 'ドラマ',
    politicaPrivacidade: 'プライバシーポリシー',
    faleConosco: 'お問い合わせ',
    versaoApp: 'アプリバージョン',
    releaseBuild: 'リリースビルド',
    criePerfilBanner: 'プロフィールを作成してエクスペリエンスをパーソナライズしましょう！',
    userPadrao: '@ユーザー',
    criar: '作成',
    editar: '編集',
    perfil: 'プロフィール',
    sair: 'サインアウト',
    voltar: '戻る',
    confirmar: '確認',
    linguagemTitulo: '言語',
    selecioneIdioma: '言語を選択',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('pt');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('yoshikawaLanguage');
      if (saved && LANGUAGES.some(l => l.code === saved)) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (lang) => {
    setLanguageState(lang);
    try { localStorage.setItem('yoshikawaLanguage', lang); } catch {}
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.pt[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
