import { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'pt', label: 'Português' },
  { code: 'es', label: 'Español' },
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' }
];

export const TRANSLATIONS = {
  pt: {
    inicio: 'Início',
    animes: 'Animes',
    favoritos: 'Favoritos',
    menu: 'Menu',
    emAlta: 'Em alta',
    novosEpisodios: 'Novos episódios',
    recemAdicionados: 'Recém adicionados',
    lancamento: 'Lançamento',
    aventura: 'Aventura',
    comedia: 'Comédia',
    romance: 'Romance',
    talvezGoste: 'Talvez você goste',
    tudo: 'Tudo',
    filmes: 'Filmes',
    series: 'Séries',
    buscar: 'O que está procurando?',
    categorias: 'Categorias',
    nenhumResultado: 'Nenhum resultado encontrado',
    nenhumFavorito: 'Nenhum favorito encontrado',
    episodio: 'Episódio',
    emExibicao: 'Em exibição',
    sinopseIndisponivel: 'Sinopse não disponível.',
    popularidade: 'Popularidade',
    criarPerfil: 'Criar perfil',
    editarPerfil: 'Editar Perfil',
    privacidade: 'Privacidade',
    ajuda: 'Ajuda',
    sobre: 'Sobre',
    linguagem: 'Linguagem',
    sairDoPerfil: 'Sair do perfil',
    sairLimpar: 'Sair e limpar dados',
    cancelar: 'Cancelar',
    aoSalvar: 'Ao sair, todos os seus favoritos serão perdidos permanentemente. Deseja continuar?',
    nome: 'Nome',
    username: 'Username',
    salvar: 'Salvar',
    entrouEm: 'Entrou em',
    hoje: 'hoje',
    privacidadeTitulo: 'Privacidade',
    privacidadeTexto: 'Este aplicativo não coleta, armazena ou compartilha dados pessoais dos usuários. As informações de perfil e favoritos são armazenadas localmente no seu dispositivo e podem ser removidas a qualquer momento.',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'Créditos',
    desenvolvedor: 'Desenvolvido por',
    design: 'Design e implementação por Yoshikawa Systems',
    direitos: 'Direitos Autorais',
    isencao: 'Isenção de Responsabilidade',
    isencaoTexto: 'Este site não hospeda nenhum conteúdo. Utiliza APIs públicas de terceiros (TMDB) para indexação de informações. Qualquer violação de direitos autorais deve ser reportada diretamente aos provedores de conteúdo.',
    versao: 'Versão',
    anime: 'Anime',
    filme: 'Filme',
    serie: 'Série',
    politicaPrivacidade: 'Política de Privacidade',
    faleConosco: 'Fale conosco',
    versaoApp: 'Versão do app',
    releaseBuild: 'RELEASE BUILD',
    criePerfilBanner: 'Crie seu perfil para personalizar sua experiência!',
    userPadrao: '@user',
    criar: 'Criar',
    editar: 'Editar',
    perfil: 'Perfil',
    sair: 'Sair',
    voltar: 'Voltar',
    confirmar: 'Confirmar',
    linguagemTitulo: 'Idioma',
    selecioneIdioma: 'Selecione o idioma',
    continuar: 'Continuar',
    assistir: 'Assistir',
    curtir: 'Curtir',
    curtiu: 'Curtiu',
    favoritar: 'Favoritar',
    favoritado: 'Favoritado',
    compartilhar: 'Compartilhar',
    verMenos: 'Ver menos',
    verMais: 'Ver mais',
    temporada: 'Temporada',
    temporadas: 'temporadas',
    antigos: 'Antigos',
    recentes: 'Recentes',
    emBreve: 'Em breve',
    assistido: 'Assistido',
    semTitulo: 'Sem título',
    duracaoIndisponivel: 'Duração indisponível',
    anterior: 'Anterior',
    proximo: 'Próximo',
    entrouNoChat: '{name} entrou no chat',
    saiuDoChat: '{name} saiu do chat',
    chatFechadoPeloCriador: 'O chat foi fechado pelo criador',
    chatEncerrado: 'O chat foi encerrado e não está mais disponível.',
    aguardandoAlguem: 'Aguardando alguém entrar...',
    seuNomeParaChat: 'Seu nome para o chat',
    digiteMensagem: 'Digite sua mensagem...',
    chatEncerradoPlaceholder: 'Chat encerrado',
    abrirChat: 'Abrir chat',
    linkInvalido: 'Este link é inválido ou o chat foi encerrado.',
    chatCheio: 'Chat cheio (máximo {max} pessoas).',
    assistirComAmigo: 'Assistir com amigo',
    facaLoginParaSalas: 'Faça login para criar salas',
    envieLinkParaAssistirJunto: 'Envie o link para assistir junto:',
    copiarLink: 'Copiar link',
    copiado: 'Copiado!',
    erroCarregarConteudo: 'Erro ao carregar conteúdo',
    voltarInicio: 'Voltar ao início',
    desconhecido: 'Desconhecido',
    generoDesconhecido: 'Gênero desconhecido',
    min: 'min',
    façaLoginParaSalas: 'Faça login para criar salas',
    ativarModoAmigo: 'Ativar modo amigo',
    desativarModoAmigo: 'Desativar modo amigo',
    compartilharPagina: 'Compartilhar página',
    preview: 'Pré-visualização',
  },
  es: {
    inicio: 'Inicio',
    animes: 'Animes',
    favoritos: 'Favoritos',
    menu: 'Menú',
    emAlta: 'En tendencia',
    novosEpisodios: 'Nuevos episodios',
    recemAdicionados: 'Recién añadidos',
    lancamento: 'Lanzamiento',
    aventura: 'Aventura',
    comedia: 'Comedia',
    romance: 'Romance',
    talvezGoste: 'Quizás te guste',
    tudo: 'Todo',
    filmes: 'Películas',
    series: 'Series',
    buscar: '¿Qué estás buscando?',
    categorias: 'Categorías',
    nenhumResultado: 'No se encontraron resultados',
    nenhumFavorito: 'No se encontraron favoritos',
    episodio: 'Episodio',
    emExibicao: 'En emisión',
    sinopseIndisponivel: 'Sinopsis no disponible.',
    popularidade: 'Popularidad',
    criarPerfil: 'Crear perfil',
    editarPerfil: 'Editar perfil',
    privacidade: 'Privacidad',
    ajuda: 'Ayuda',
    sobre: 'Acerca de',
    linguagem: 'Idioma',
    sairDoPerfil: 'Salir del perfil',
    sairLimpar: 'Salir y borrar datos',
    cancelar: 'Cancelar',
    aoSalvar: 'Al salir, todos tus favoritos se perderán permanentemente. ¿Deseas continuar?',
    nome: 'Nombre',
    username: 'Usuario',
    salvar: 'Guardar',
    entrouEm: 'Se unió en',
    hoje: 'hoy',
    privacidadeTitulo: 'Privacidad',
    privacidadeTexto: 'Esta aplicación no recopila, almacena ni comparte datos personales de los usuarios. La información del perfil y los favoritos se almacenan localmente en tu dispositivo y se pueden eliminar en cualquier momento.',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'Créditos',
    desenvolvedor: 'Desarrollado por',
    design: 'Diseño e implementación por Yoshikawa Systems',
    direitos: 'Derechos de autor',
    isencao: 'Descargo de responsabilidad',
    isencaoTexto: 'Este sitio no aloja ningún contenido. Utiliza APIs públicas de terceros (TMDB) para indexar información. Cualquier infracción de derechos de autor debe informarse directamente a los proveedores de contenido.',
    versao: 'Versión',
    anime: 'Anime',
    filme: 'Película',
    serie: 'Serie',
    politicaPrivacidade: 'Política de privacidad',
    faleConosco: 'Contáctanos',
    versaoApp: 'Versión de la app',
    releaseBuild: 'VERSIÓN DE LANZAMIENTO',
    criePerfilBanner: '¡Crea tu perfil para personalizar tu experiencia!',
    userPadrao: '@usuario',
    criar: 'Crear',
    editar: 'Editar',
    perfil: 'Perfil',
    sair: 'Salir',
    voltar: 'Volver',
    confirmar: 'Confirmar',
    linguagemTitulo: 'Idioma',
    selecioneIdioma: 'Seleccionar idioma',
    continuar: 'Continuar',
    assistir: 'Ver',
    curtir: 'Me gusta',
    curtiu: 'Gusta',
    favoritar: 'Favorito',
    favoritado: 'Favorito',
    compartilhar: 'Compartir',
    verMenos: 'Ver menos',
    verMais: 'Ver más',
    temporada: 'Temporada',
    temporadas: 'temporadas',
    antigos: 'Antiguos',
    recentes: 'Recientes',
    emBreve: 'Próximamente',
    assistido: 'Visto',
    semTitulo: 'Sin título',
    duracaoIndisponivel: 'Duración no disponible',
    anterior: 'Anterior',
    proximo: 'Siguiente',
    entrouNoChat: '{name} entró al chat',
    saiuDoChat: '{name} salió del chat',
    chatFechadoPeloCriador: 'El chat fue cerrado por el creador',
    chatEncerrado: 'El chat ha finalizado y ya no está disponible.',
    aguardandoAlguem: 'Esperando que alguien entre...',
    seuNomeParaChat: 'Tu nombre para el chat',
    digiteMensagem: 'Escribe tu mensaje...',
    chatEncerradoPlaceholder: 'Chat cerrado',
    abrirChat: 'Abrir chat',
    linkInvalido: 'Este enlace no es válido o el chat ha finalizado.',
    chatCheio: 'Chat lleno (máximo {max} personas).',
    assistirComAmigo: 'Ver con un amigo',
    facaLoginParaSalas: 'Inicia sesión para crear salas',
    envieLinkParaAssistirJunto: 'Envía el enlace para ver juntos:',
    copiarLink: 'Copiar enlace',
    copiado: '¡Copiado!',
    erroCarregarConteudo: 'Error al cargar el contenido',
    voltarInicio: 'Volver al inicio',
    desconhecido: 'Desconocido',
    generoDesconhecido: 'Género desconocido',
    min: 'min',
    façaLoginParaSalas: 'Inicia sesión para crear salas',
    ativarModoAmigo: 'Activar modo amigo',
    desativarModoAmigo: 'Desactivar modo amigo',
    compartilharPagina: 'Compartir página',
    preview: 'Previsualización',
  },
  en: {
    inicio: 'Home',
    animes: 'Animes',
    favoritos: 'Favorites',
    menu: 'Menu',
    emAlta: 'Trending',
    novosEpisodios: 'New Episodes',
    recemAdicionados: 'Recently Added',
    lancamento: 'Now Playing',
    aventura: 'Adventure',
    comedia: 'Comedy',
    romance: 'Romance',
    talvezGoste: 'You Might Like',
    tudo: 'All',
    filmes: 'Movies',
    series: 'TV Shows',
    buscar: 'What are you looking for?',
    categorias: 'Categories',
    nenhumResultado: 'No results found',
    nenhumFavorito: 'No favorites found',
    episodio: 'Episode',
    emExibicao: 'Airing',
    sinopseIndisponivel: 'Synopsis not available.',
    popularidade: 'Popularity',
    criarPerfil: 'Create Profile',
    editarPerfil: 'Edit Profile',
    privacidade: 'Privacy',
    ajuda: 'Help',
    sobre: 'About',
    linguagem: 'Language',
    sairDoPerfil: 'Sign Out',
    sairLimpar: 'Sign out and clear data',
    cancelar: 'Cancel',
    aoSalvar: 'By signing out, all your favorites will be permanently lost. Do you wish to continue?',
    nome: 'Name',
    username: 'Username',
    salvar: 'Save',
    entrouEm: 'Joined in',
    hoje: 'today',
    privacidadeTitulo: 'Privacy',
    privacidadeTexto: 'This app does not collect, store, or share personal data. Profile and favorites are stored locally on your device and can be removed at any time.',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'Credits',
    desenvolvedor: 'Developed by',
    design: 'Design and implementation by Yoshikawa Systems',
    direitos: 'Copyright',
    isencao: 'Disclaimer',
    isencaoTexto: 'This site does not host any content. It uses public third-party APIs (TMDB) for content indexing. Any copyright infringement should be reported directly to the content providers.',
    versao: 'Version',
    anime: 'Anime',
    filme: 'Movie',
    serie: 'TV Show',
    politicaPrivacidade: 'Privacy Policy',
    faleConosco: 'Contact us',
    versaoApp: 'App version',
    releaseBuild: 'RELEASE BUILD',
    criePerfilBanner: 'Create your profile to personalize your experience!',
    userPadrao: '@user',
    criar: 'Create',
    editar: 'Edit',
    perfil: 'Profile',
    sair: 'Sign out',
    voltar: 'Back',
    confirmar: 'Confirm',
    linguagemTitulo: 'Language',
    selecioneIdioma: 'Select language',
    continuar: 'Continue',
    assistir: 'Watch',
    curtir: 'Like',
    curtiu: 'Liked',
    favoritar: 'Favorite',
    favoritado: 'Favorited',
    compartilhar: 'Share',
    verMenos: 'Show less',
    verMais: 'Show more',
    temporada: 'Season',
    temporadas: 'seasons',
    antigos: 'Oldest',
    recentes: 'Newest',
    emBreve: 'Coming soon',
    assistido: 'Watched',
    semTitulo: 'Untitled',
    duracaoIndisponivel: 'Duration unavailable',
    anterior: 'Previous',
    proximo: 'Next',
    entrouNoChat: '{name} joined the chat',
    saiuDoChat: '{name} left the chat',
    chatFechadoPeloCriador: 'The chat was closed by the creator',
    chatEncerrado: 'The chat has ended and is no longer available.',
    aguardandoAlguem: 'Waiting for someone to join...',
    seuNomeParaChat: 'Your chat name',
    digiteMensagem: 'Type your message...',
    chatEncerradoPlaceholder: 'Chat closed',
    abrirChat: 'Open chat',
    linkInvalido: 'This link is invalid or the chat has ended.',
    chatCheio: 'Chat full (max {max} people).',
    assistirComAmigo: 'Watch with a friend',
    facaLoginParaSalas: 'Log in to create rooms',
    envieLinkParaAssistirJunto: 'Send the link to watch together:',
    copiarLink: 'Copy link',
    copiado: 'Copied!',
    erroCarregarConteudo: 'Error loading content',
    voltarInicio: 'Back to home',
    desconhecido: 'Unknown',
    generoDesconhecido: 'Unknown genre',
    min: 'min',
    façaLoginParaSalas: 'Log in to create rooms',
    ativarModoAmigo: 'Enable friend mode',
    desativarModoAmigo: 'Disable friend mode',
    compartilharPagina: 'Share page',
    preview: 'Preview',
  },
  ja: {
    inicio: 'ホーム',
    animes: 'アニメ',
    favoritos: 'お気に入り',
    menu: 'メニュー',
    emAlta: 'トレンド',
    novosEpisodios: '新エピソード',
    recemAdicionados: '最近追加',
    lancamento: '公開中',
    aventura: '冒険',
    comedia: 'コメディ',
    romance: 'ロマンス',
    talvezGoste: 'おすすめ',
    tudo: 'すべて',
    filmes: '映画',
    series: 'ドラマ',
    buscar: '何をお探しですか？',
    categorias: 'カテゴリ',
    nenhumResultado: '結果が見つかりません',
    nenhumFavorito: 'お気に入りがありません',
    episodio: 'エピソード',
    emExibicao: '放送中',
    sinopseIndisponivel: '概要はありません。',
    popularidade: '人気',
    criarPerfil: 'プロフィール作成',
    editarPerfil: 'プロフィール編集',
    privacidade: 'プライバシー',
    ajuda: 'ヘルプ',
    sobre: 'について',
    linguagem: '言語',
    sairDoPerfil: 'サインアウト',
    sairLimpar: 'サインアウトしてデータを消去',
    cancelar: 'キャンセル',
    aoSalvar: 'サインアウトすると、お気に入りが完全に失われます。続行しますか？',
    nome: '名前',
    username: 'ユーザー名',
    salvar: '保存',
    entrouEm: '参加日',
    hoje: '今日',
    privacidadeTitulo: 'プライバシー',
    privacidadeTexto: 'このアプリは個人データを収集、保存、共有しません。プロフィールとお気に入りはデバイスにローカルに保存され、いつでも削除できます。',
    sobreTitulo: 'Yoshikawa Player',
    creditos: 'クレジット',
    desenvolvedor: '開発者',
    design: 'Yoshikawa Systemsによるデザインと実装',
    direitos: '著作権',
    isencao: '免責事項',
    isencaoTexto: 'このサイトはコンテンツをホストしていません。公開されているサードパーティAPI（TMDB）を使用して情報をインデックスしています。著作権侵害は、直接コンテンツ提供者に報告してください。',
    versao: 'バージョン',
    anime: 'アニメ',
    filme: '映画',
    serie: 'ドラマ',
    politicaPrivacidade: 'プライバシーポリシー',
    faleConosco: 'お問い合わせ',
    versaoApp: 'アプリバージョン',
    releaseBuild: 'リリースビルド',
    criePerfilBanner: 'プロフィールを作成してエクスペリエンスをパーソナライズしましょう！',
    userPadrao: '@ユーザー',
    criar: '作成',
    editar: '編集',
    perfil: 'プロフィール',
    sair: 'サインアウト',
    voltar: '戻る',
    confirmar: '確認',
    linguagemTitulo: '言語',
    selecioneIdioma: '言語を選択',
    continuar: '続ける',
    assistir: '視聴',
    curtir: 'いいね',
    curtiu: 'いいね済み',
    favoritar: 'お気に入り',
    favoritado: 'お気に入り済み',
    compartilhar: '共有',
    verMenos: '折りたたむ',
    verMais: 'もっと見る',
    temporada: 'シーズン',
    temporadas: 'シーズン',
    antigos: '古い順',
    recentes: '新しい順',
    emBreve: '近日公開',
    assistido: '視聴済み',
    semTitulo: 'タイトルなし',
    duracaoIndisponivel: '時間不明',
    anterior: '前へ',
    proximo: '次へ',
    entrouNoChat: '{name}がチャットに参加しました',
    saiuDoChat: '{name}がチャットから退出しました',
    chatFechadoPeloCriador: '作成者によってチャットが閉じられました',
    chatEncerrado: 'チャットは終了し、利用できなくなりました。',
    aguardandoAlguem: '誰かが参加するのを待っています...',
    seuNomeParaChat: 'チャット用の名前',
    digiteMensagem: 'メッセージを入力...',
    chatEncerradoPlaceholder: 'チャット終了',
    abrirChat: 'チャットを開く',
    linkInvalido: 'このリンクは無効か、チャットが終了しています。',
    chatCheio: 'チャット満員（最大{max}人）',
    assistirComAmigo: '友達と視聴',
    facaLoginParaSalas: 'ルーム作成にはログインしてください',
    envieLinkParaAssistirJunto: '一緒に視聴するリンクを送ってください：',
    copiarLink: 'リンクをコピー',
    copiado: 'コピーしました！',
    erroCarregarConteudo: 'コンテンツの読み込みエラー',
    voltarInicio: 'ホームに戻る',
    desconhecido: '不明',
    generoDesconhecido: '不明なジャンル',
    min: '分',
    façaLoginParaSalas: 'ルーム作成にはログインしてください',
    ativarModoAmigo: 'フレンドモードを有効にする',
    desativarModoAmigo: 'フレンドモードを無効にする',
    compartilharPagina: 'ページを共有',
    preview: 'プレビュー',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('pt');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('yoshikawaLanguage');
      if (saved && LANGUAGES.some(l => l.code === saved)) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (lang) => {
    setLanguageState(lang);
    try { localStorage.setItem('yoshikawaLanguage', lang); } catch {}
  };

  const t = (key, params = {}) => {
    let text = TRANSLATIONS[language]?.[key] || TRANSLATIONS.pt[key] || key;
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
